### ISSUE TITLE
Error building other nebula plugin

### ISSUE THREAD

**Issue by grv87** [nebula-plugins/nebula-plugin-plugin#36]
I'm trying to build https://github.com/nebula-plugins/gradle-info-plugin (tagged version v3.6.0) and have the following error:
```
An exception occurred applying plugin request [id: 'nebula.plugin-plugin', version: '5.9.0']
> Failed to apply plugin [id 'nebula.provided-base']
   > This plugin is not compatible with Gradle 3.4 and later. Use the 'compileOnly' configuration
```
I'm not sure which plugin is broken but at least one is.

**Comment by DanielThomas** [comment]
The plugin might have been published with dynamic version constraints due to an issue with plugin portal publishing, which causes the extra configurations plugin to be upgraded. 

If you really need to build at this tag, upgrade the plugin-plugin - the info plugin moves pretty slowly however, chances are you can do whatever you need on HEAD.
